test input:

diff --git a/.github/workflows/deployment.yaml b/.github/workflows/deployment.yaml
--- a/.github/workflows/deployment.yaml
+++ b/.github/workflows/deployment.yaml
@@ -4,30 +4,19 @@ on:
   workflow_dispatch:
     inputs:
       network:
-        description: "Network"
+        description: "Select Network"
         required: true
         type: choice
         options:
           - "Baobab"
-          - "Cypress"    
+          - "Cypress"
       application:
-        description: "Service"
+        description: "Select Application"
         required: true
-        type: choice
-        options:
-          - "cli"
-          - "aggregator"
-          - "vrf"
-          - "api"
-          - "request-response"
-          - "delegator"
-          - "fetcher"
-          - "por"
-          - "node"
-          - "boot-api"
-          - "sentinel"
+        type: string
+        default: "default" # Temporary default to allow workflow to start
       image:
-        description: "Image Version"
+        description: "Select Image Version"
         required: true
         type: choice
         default: "new"
@@ -35,204 +24,62 @@ on:
           - "new"
 
 jobs:
-  prepare:
-    name: Prepare
+  set-application-options:
+    name: Set Application Options
     runs-on: ubuntu-latest
-    if: ${{ github.event.inputs.network == 'Baobab' }}
-
     outputs:
-      tag_date: ${{ steps.tag.outputs.date }}
-      tag_git_hash: ${{ steps.tag.outputs.git_hash }}
-      service: ${{ steps.tag.outputs.service }}
-      ecr_url: ${{ steps.tag.outputs.ecr_url }}
-      version: ${{ steps.package.outputs.version }}
-
+      applications: ${{ steps.set-vars.outputs.applications }}
+    
     steps:
-      - uses: actions/checkout@master
-
-      - name: Get time TAG
-        id: tag
-        run: |
-          echo "date=$(date +'%Y%m%d.%H%M')" >> $GITHUB_OUTPUT
-          echo "git_hash=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
-          service="${{ github.event.inputs.application }}"
-          if [[ "${{ github.event.inputs.application }}" == "vrf" || "${{ github.event.inputs.application }}" == "request-response" || "${{ github.event.inputs.application }}" == "aggregator" ]]; then
-            service="core"
-          fi            
-          echo "service=$service" >> $GITHUB_OUTPUT
-          echo "ecr_url=public.ecr.aws/bisonai/orakl-${service}" >> $GITHUB_OUTPUT
-
-      - name: Get package version
-        id: package
-        run: |
-          if [[ "${{ steps.tag.outputs.service }}" == "cli" || "${{ steps.tag.outputs.service }}" == "fetcher" || "${{ steps.tag.outputs.service }}" == "core" ]]; then
-            echo "version=$(node -p -e "require('./"${{ steps.tag.outputs.service }}"/package.json').version")" >> $GITHUB_OUTPUT
-          else 
-            if [[ "${{ steps.tag.outputs.service }}" == "boot-api" ]]; then
-              version=$(cat ./node/.version)
-            else
-              version=$(cat ./${{ steps.tag.outputs.service }}/.version)
-            fi
-            echo "version=$version" >> $GITHUB_OUTPUT
-          fi
-
-  build:
-    name: Build
-    runs-on: ubuntu-latest
-    needs: prepare
-    if: ${{ github.event.inputs.network == 'Baobab' }}
-
-    permissions:
-      id-token: write
-      contents: read
-
-    outputs:
-      img_tag: ${{ steps.img-tag.outputs.img_tag }}
-
-    steps:
-      - uses: actions/checkout@master
-
-      - name: Setup Go
-        uses: actions/setup-go@v4
-        with:
-          go-version: "1.22.3"
-          check-latest: true
-          cache-dependency-path: |
-            ./${{ needs.prepare.outputs.service }}/go.sum
-            ./${{ needs.prepare.outputs.service }}/go.mod
-        if: ${{ needs.prepare.outputs.service != 'core' || needs.prepare.outputs.service != 'fetcher' || needs.prepare.outputs.service != 'cli' }}
-
-      - name: docker build ${{ github.event.inputs.application }}
-        run: SERVICE_NAME=orakl-${{ needs.prepare.outputs.service }} docker compose -f docker-compose.build.yaml build
-
-      - name: configure aws credentials
-        uses: aws-actions/configure-aws-credentials@v2
-        with:
-          aws-region: us-east-1
-          role-to-assume: ${{ secrets.ROLE_ARN }}
-
-      - name: login to amazon ecr
-        id: login-ecr-public
-        uses: aws-actions/amazon-ecr-login@v1
-        with:
-          registry-type: public
-
-      - name: publish image to ecr
-        run: |
-          docker tag orakl-${{ needs.prepare.outputs.service }} ${{ needs.prepare.outputs.ecr_url }}:latest
-          docker push ${{ needs.prepare.outputs.ecr_url }}:latest
-          docker tag ${{ needs.prepare.outputs.ecr_url }}:latest ${{ needs.prepare.outputs.ecr_url }}:v${{ needs.prepare.outputs.version }}.${{ needs.prepare.outputs.tag_date }}.${{ needs.prepare.outputs.tag_git_hash }}
-          docker push ${{ needs.prepare.outputs.ecr_url }}:v${{ needs.prepare.outputs.version }}.${{ needs.prepare.outputs.tag_date }}.${{ needs.prepare.outputs.tag_git_hash }}
-
-      - name: image tag output
-        id: img-tag
-        run: echo "img_tag=v${{ needs.prepare.outputs.version }}.${{ needs.prepare.outputs.tag_date }}.${{ needs.prepare.outputs.tag_git_hash }}" >> $GITHUB_OUTPUT
-
-  post-slack-image-upload:
-    name: Slack message for image upload
-    needs: [prepare, build]
-    uses: ./.github/workflows/post.slack.yaml
-    with:
-      status: "Success"
-      slack-message: "${{ github.event.inputs.network }} ${{ github.event.inputs.application }}* : *${{ needs.prepare.outputs.service }}* ${{ needs.prepare.outputs.version }}.${{ needs.prepare.outputs.tag_date }}.${{ needs.prepare.outputs.tag_git_hash }} is uploaded"
-    secrets:
-      SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
-    if: ${{ github.event.inputs.network == 'Baobab' && success() }}
-
-  image-update:
-    name: Update image tag
-    needs: [prepare, build]
-    uses: ./.github/workflows/update.image-tag.yaml
-    with:
-      network: "baobab"
-      project-name: ${{ github.event.inputs.application }}
-      version: ${{ needs.prepare.outputs.version }}
-      image-tag: ${{ needs.build.outputs.img_tag }}
-      tag_date: ${{ needs.prepare.outputs.tag_date }}
-      tag_git_hash: ${{ needs.prepare.outputs.tag_git_hash }}
-    secrets:
-      PAT: ${{ secrets.PAT }}
-    if: ${{ github.event.inputs.network == 'Baobab' }}
-
-  post-slack-baobab-tag-update-success:
-    name: Post slack message for tag update success
-    needs: [prepare, build, image-update]
-    uses: ./.github/workflows/post.slack.yaml
-    with:
-      status: "Success"
-      slack-message: "${{ github.event.inputs.network }} *${{ github.event.inputs.application }}* : *${{ needs.prepare.outputs.service }}* new image tag ${{ needs.prepare.outputs.version }}.${{ needs.prepare.outputs.tag_date }}.${{ needs.prepare.outputs.tag_git_hash }} is updated"
-    secrets:
-      SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
-    if: ${{ github.event.inputs.network == 'Baobab' && success() }}
-
-  cypress-image-update:
-    name: cypress image update
-    uses: ./.github/workflows/update.image-tag.yaml
-    with:
-      network: "cypress"
-      project-name: ${{ github.event.inputs.application }}
-    secrets:
-      PAT: ${{ secrets.PAT }}
-    if: ${{ github.event.inputs.network == 'Cypress' }}
-
-  post-slack-cypress-tag-update-success:
-    name: Post slack message for tag update success
-    needs: [cypress-image-update]
-    uses: ./.github/workflows/post.slack.yaml
-    with:
-      status: "Success"
-      slack-message: "${{ github.event.inputs.network }} *${{ github.event.inputs.application }}* is updated"
-    secrets:
-      SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
-    if: ${{ github.event.inputs.network == 'Cypress' && success() }}
-
-  post-slack-tag-update-failure:
-    name: Post to a slack message for tag update failure
-    needs: [prepare, build, image-update]
-    uses: ./.github/workflows/post.slack.yaml
-    with:
-      status: "Failed"
-      slack-message: "${{ github.event.inputs.network }} *${{ github.event.inputs.application }}* git action failed"
-    secrets:
-      SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
-    if: ${{ github.event.inputs.network == 'Baobab' && failure() }}
-
-  update-workflow-and-readme:
-    name: Update Workflow and README
-    runs-on: ubuntu-latest
-    needs: [image-update]
-    steps:
-      - name: Checkout Repository
+      - name: Checkout code
         uses: actions/checkout@v2
 
-      - name: Get Latest PR Title and Description
-        id: pr_info
-        run: |
-          PR_TITLE=$(gh pr view ${GITHUB_REF} --json title -q ".title")
-          PR_DESCRIPTION=$(gh pr view ${GITHUB_REF} --json body -q ".body")
-          echo "pr_title=${PR_TITLE}" >> $GITHUB_ENV
-          echo "pr_description=${PR_DESCRIPTION}" >> $GITHUB_ENV
+      - name: Set up GitHub CLI
+        uses: cli/gh-action@v2
+        with:
+          token: ${{ secrets.GITHUB_TOKEN }}
 
-      - name: Update Workflow Dispatch Options
+      - name: Determine Applications
+        id: set-vars
         run: |
-          NEW_TAG=${{ github.event.inputs.application }}/${{ needs.build.outputs.img_tag }}
-          sed -i "/options:/a\          - \"${NEW_TAG}\"" .github/workflows/deployment.yaml
-          git add .github/workflows/deployment.yaml
+          if [ "${{ github.event.inputs.network }}" == "Baobab" ]; then
+            applications="cli,aggregator,vrf,api"
+          elif [ "${{ github.event.inputs.network }}" == "Cypress" ]; then
+            applications="request-response,delegator,fetcher,por"
+          else
+            applications="default"
+          fi
+          echo "applications=${applications}" >> $GITHUB_OUTPUT
 
-      - name: Update README with Latest PR Info
-        run: |
-          echo "### ${NEW_TAG}" >> README.md
-          echo "#### PR Title" >> README.md
-          echo "${{ env.pr_title }}" >> README.md
-          echo "#### PR Description" >> README.md
-          echo "${{ env.pr_description }}" >> README.md
-          git add README.md
+  display-application-options:
+    name: Display Application Options
+    runs-on: ubuntu-latest
+    needs: set-application-options
 
-      - name: Commit and Push Changes
+    steps:
+      - name: Output Applications
         run: |
-          git config --global user.name 'github-actions'
-          git config --global user.email 'github-actions@github.com'
-          git commit -m "Update workflow dispatch options and README with new image tag ${NEW_TAG}"
-          git push
-        env:
-          GITHUB_TOKEN: ${{ github.token }}
+          echo "Available applications for ${GITHUB_EVENT_INPUTS_NETWORK}: ${needs.set-application-options.outputs.applications}"
+
+  deploy:
+    name: Deploy
+    runs-on: ubuntu-latest
+    needs: set-application-options
+    if: always()
+
+    steps:
+      - name: Checkout code
+        uses: actions/checkout@v2
+
+      - name: Validate Application
+        run: |
+          valid_applications="${{ needs.set-application-options.outputs.applications }}"
+          IFS=',' read -ra APP_ARRAY <<< "$valid_applications"
+          if [[ ! " ${APP_ARRAY[@]} " =~ " ${GITHUB_EVENT_INPUTS_APPLICATION} " ]]; then
+            echo "Invalid application ${GITHUB_EVENT_INPUTS_APPLICATION} for network ${GITHUB_EVENT_INPUTS_NETWORK}"
+            exit 1
+          fi
+
+      - name: Run Deployment
+        run: |
+          echo "Deploying to ${GITHUB_EVENT_INPUTS_NETWORK} with application ${GITHUB_EVENT_INPUTS_APPLICATION} and image ${GITHUB_EVENT_INPUTS_IMAGE}"
